!
!  BOUNGlobal.f90 - This file contains the global data and functions
!  for the COM Server
!
!  Generated by the Visual Fortran COM Server Wizard on
!  06/20/08 at 11:42:58.
!
!   DO NOT EDIT THIS FILE!
!
!  This file is re-generated every time the object hierarchy is changed.
!

!
!  M O D U L E S
!

!  Module containg DLL global data

module BOUN_Global
    use dfwinty
    use kernel32
    use IClassFactory_Types

    integer(HANDLE) ghinst
    integer         gCntLock
    type (T_RTL_CRITICAL_SECTION) gGlobalCriticalSection
    !  Per Class
    integer(INT_PTR_KIND()) gUnicodeNotationIClassFactory
    type (IClassFactory_Data), pointer :: gpUnicodeNotationCFData
    integer(INT_PTR_KIND()) gUnicodeNotationITypeInfo

	! Type Library GUID		
	TYPE (GUID), PARAMETER :: GUID_TypeLib_BOUN = &
		GUID(#A3F9F222, #462D, #4412, &
        CHAR('A5'X)//CHAR('B9'X)//CHAR('AB'X)//CHAR('75'X)// &
        CHAR('43'X)//CHAR('C9'X)//CHAR('38'X)//CHAR('7B'X))

  contains

    integer function ServerLock ()
        integer(LONG) r
        r = InterlockedIncrement (loc(gCntLock)) 
        ServerLock = gCntLock
    end function

    integer function ServerUnlock ()
        integer(LONG) r
        r = InterlockedDecrement (loc(gCntLock)) 
        ServerUnlock = gCntLock
    end function

end module BOUN_Global

