!
!  IUnicodeNotation.f90 - This module contains the interfaces of methods 
!  of the IUnicodeNotation interface
!
!  Generated by the Visual Fortran COM Server Wizard on
!  06/20/08 at 11:42:58.
!
!   DO NOT EDIT THIS FILE!
!
!  This file is re-generated every time the object hierarchy is changed.
!

module IUnicodeNotation_Methods

    !  These routines get implemented by the user
    interface 
        function IUnicodeNotation_Notate( ObjectData ,&
                 sString,&
                 nLen,&
                 aArray) result (hresult)
            use UnicodeNotation_Types
            type(UnicodeNotation_InstanceData) ObjectData
            !dec$ attributes reference :: ObjectData
            TYPE(VARIANT), intent(in) :: sString
            INTEGER(4), intent(in) :: nLen
            TYPE(VARIANT), intent(out) :: aArray
            integer(LONG) hresult
        end function
        function IUnicodeNotation_get_Coalesce( ObjectData ,&
                 VALUE) result (hresult)
            use UnicodeNotation_Types
            type(UnicodeNotation_InstanceData) ObjectData
            !dec$ attributes reference :: ObjectData
            LOGICAL(2), intent(out) :: VALUE
            integer(LONG) hresult
        end function
        function IUnicodeNotation_put_Coalesce( ObjectData ,&
                 VALUE) result (hresult)
            use UnicodeNotation_Types
            type(UnicodeNotation_InstanceData) ObjectData
            !dec$ attributes reference :: ObjectData
            LOGICAL(2), intent(in) :: VALUE
            integer(LONG) hresult
        end function
        function IUnicodeNotation_Generate( ObjectData ,&
                 sInput,&
                 sOutput) result (hresult)
            use UnicodeNotation_Types
            type(UnicodeNotation_InstanceData) ObjectData
            !dec$ attributes reference :: ObjectData
            TYPE(VARIANT), intent(in) :: sInput
            TYPE(VARIANT), intent(out) :: sOutput
            integer(LONG) hresult
        end function

    end interface

    !  Local definition of SysStringLen
    interface
        PURE INTEGER*4 FUNCTION SysStringLen_Local(bstr);
            !DEC$IF DEFINED(_X86_)
            !DEC$ ATTRIBUTES DEFAULT, STDCALL, ALIAS : '_SysStringLen@' :: SysStringLen_Local
            !DEC$ELSE
            !DEC$ ATTRIBUTES DEFAULT, STDCALL, ALIAS : 'SysStringLen' :: SysStringLen_Local
            !DEC$ENDIF
            USE DFWINTY
            INTEGER(INT_PTR_KIND()), INTENT(IN)    :: bstr
            !DEC$ ATTRIBUTES VALUE              :: bstr
        END FUNCTION SysStringLen_Local
    end interface

  contains

    !  Wrapper functions called from the Vtbl

    function $IUnicodeNotation_Notate( pInterface ,&
             sString ,&
             nLen ,&
             aArray ) result (hresult)
        !DEC$ ATTRIBUTES STDCALL :: $IUnicodeNotation_Notate
        use UnicodeNotation_Types
        use dfcom
        use dflib
        implicit none
        type (IUnicodeNotation_Ptr) pInterface
        !dec$ attributes reference :: pInterface
        TYPE(VARIANT), intent(in) :: sString 
        !DEC$ ATTRIBUTES value :: sString 
        INTEGER(4), intent(in) :: nLen 
        !DEC$ ATTRIBUTES value :: nLen 
        TYPE(VARIANT), intent(out) :: aArray 
        !DEC$ ATTRIBUTES reference :: aArray 
        integer(LONG) hresult
        integer i
		

        hresult = IUnicodeNotation_Notate(pInterface % pInternalData % pInstanceData ,&
             sString ,&
             nLen ,&
             aArray )
        
        if (hresult < 0) goto 9999
    9999  continue  ! Cleanup code
    end function
    function $IUnicodeNotation_get_Coalesce( pInterface ,&
             VALUE ) result (hresult)
        !DEC$ ATTRIBUTES STDCALL :: $IUnicodeNotation_get_Coalesce
        use UnicodeNotation_Types
        use dfcom
        use dflib
        implicit none
        type (IUnicodeNotation_Ptr) pInterface
        !dec$ attributes reference :: pInterface
        LOGICAL(2), intent(out) :: VALUE 
        !DEC$ ATTRIBUTES reference :: VALUE 
        integer(LONG) hresult
        integer i
		

        hresult = IUnicodeNotation_get_Coalesce(pInterface % pInternalData % pInstanceData ,&
             VALUE )
        
        if (hresult < 0) goto 9999
    9999  continue  ! Cleanup code
    end function
    function $IUnicodeNotation_put_Coalesce( pInterface ,&
             VALUE ) result (hresult)
        !DEC$ ATTRIBUTES STDCALL :: $IUnicodeNotation_put_Coalesce
        use UnicodeNotation_Types
        use dfcom
        use dflib
        implicit none
        type (IUnicodeNotation_Ptr) pInterface
        !dec$ attributes reference :: pInterface
        LOGICAL(2), intent(in) :: VALUE 
        !DEC$ ATTRIBUTES value :: VALUE 
        integer(LONG) hresult
        integer i
		

        hresult = IUnicodeNotation_put_Coalesce(pInterface % pInternalData % pInstanceData ,&
             VALUE )
        
        if (hresult < 0) goto 9999
    9999  continue  ! Cleanup code
    end function
    function $IUnicodeNotation_Generate( pInterface ,&
             sInput ,&
             sOutput ) result (hresult)
        !DEC$ ATTRIBUTES STDCALL :: $IUnicodeNotation_Generate
        use UnicodeNotation_Types
        use dfcom
        use dflib
        implicit none
        type (IUnicodeNotation_Ptr) pInterface
        !dec$ attributes reference :: pInterface
        TYPE(VARIANT), intent(in) :: sInput 
        !DEC$ ATTRIBUTES value :: sInput 
        TYPE(VARIANT), intent(out) :: sOutput 
        !DEC$ ATTRIBUTES reference :: sOutput 
        integer(LONG) hresult
        integer i
		

        hresult = IUnicodeNotation_Generate(pInterface % pInternalData % pInstanceData ,&
             sInput ,&
             sOutput )
        
        if (hresult < 0) goto 9999
    9999  continue  ! Cleanup code
    end function
end module

